package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.sql.SQLException;
import java.time.LocalDate;

import javax.swing.JOptionPane;

import com.jfoenix.controls.JFXButton;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;

import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.control.DatePicker;

public class add_suppliersController {
	@FXML
	private TextArea Jtxt_address;
	@FXML
	private ImageView Jlbl_img;
	@FXML
	private TextField Jtxt_supplierid;
	@FXML
	private TextField Jtxt_lname;
	@FXML
	private TextField Jtxt_fname;
	@FXML
	private TextField Jtxt_tno;
	@FXML
	private TextField Jtxt_nic;
	@FXML
	private TextField Jtxt_email;
	@FXML
	private TextField Jtxt_cname;
	@FXML
	private ComboBox Jcombo_gender;
	@FXML
	private DatePicker Jdate_dob;
	@FXML
	private JFXButton Jbtn_submit;
	@FXML
	private JFXButton Jbtn_back;

	// Event Listener on JFXButton[#Jbtn_back].onAction
	@FXML
	public void btn_back(ActionEvent event) throws Exception{
		// TODO Autogenerated
		((Node)event.getSource()).getScene().getWindow().hide();
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("/application/ViewSuppliers.fxml"));
		Scene scene = new Scene(root);
		scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		primaryStage.initStyle(StageStyle.UNDECORATED);
		primaryStage.setScene(scene);
		primaryStage.show();
	}
	
	 public void btn_submit(ActionEvent event)throws Exception{
		 try{
			 Connection c = (Connection) DBcon.ConnerDb();
			 String sql = "insert into supplier values (?,?,?,?,?,null,?,?,?,?,null)";
			 PreparedStatement ps= (PreparedStatement) c.prepareStatement(sql);
			 ps.setString(1, Jtxt_supplierid.getText());
			 ps.setString(2, Jtxt_fname.getText());
			 ps.setString(3, Jtxt_lname.getText());
			 ps.setString(4, Jtxt_address.getText());
			 LocalDate ld = Jdate_dob.getValue();
			 ps.setString(5, ld.toString());
			 //ps.setString(6, Jcombo_gender.getSelectionModel().toString());
			 ps.setString(6, Jtxt_email.getText());
			 ps.setInt(7, Integer.parseInt(Jtxt_tno.getText()));
			 ps.setString(8, Jtxt_nic.getText());
			 ps.setString(9, Jtxt_supplierid.getText());
			  int i=ps.executeUpdate();
	             if(i>0){
	             JOptionPane.showMessageDialog(null, "Insert succefull");
//	             clear();
	             ///
	             }
	             else{   
	              JOptionPane.showMessageDialog(null, "Insert unsuccefull");
	                     } 
		 }
		 catch(SQLException e){
			 System.out.println(e); 
		 } 
	 }
}
