package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.PieChart.Data;
import javafx.scene.control.ComboBox;

import java.net.URL;
import java.sql.ResultSet;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class SalesAnalysisController implements Initializable {
	@FXML
	private AnchorPane pan1;
	@FXML
	private PieChart Jgraph_cat;
	@FXML
	private JFXButton Jbtn_gen;
	@FXML
	private PieChart Jgraph_scat;
	@FXML
	private JFXButton Jbtn_gen1;
	@FXML
	private JFXButton Jbtn_reports;
	

	// Event Listener on JFXButton[#Jbtn_gen].onAction
	/*    ObservableList<String> catlist = FXCollections.observableArrayList();
	ObservableList<String> month = FXCollections.observableArrayList("January","February","March","April","May","June","July","August","September","November","December");
	public void addvaluetocatcombo(){
		try{	
			Connection c = (Connection) DBcon.ConnerDb();
			String q = "select * from category" ;
			PreparedStatement ps = (PreparedStatement) c.prepareStatement(q);
			ResultSet rs=ps.executeQuery();
			while(rs.next()){
				catlist.add(rs.getString(2));	
			}
			rs.close();
		}
		catch(Exception e){
			System.err.println(e);	
			}	
		}*/
	@FXML
	public void genarete_piechart(ActionEvent event) {
		// TODO Autogenerated
	//	String month = Jcombo_cmonth.getValue();
	//	System.out.println(month);
		//int mnth = Integer.parseInt();
		float qty=0;float gcount=0;float wcount=0;float ccount=0;float kcount=0;
		try{
			Connection c = (Connection) DBcon.ConnerDb();
			String q = "select * from tems";
			PreparedStatement ps = (PreparedStatement) c.prepareStatement(q);
			ResultSet rs = ps.executeQuery();
			while(rs.next()){
				int amount = Integer.parseInt(rs.getString(5));
				
				qty=qty+amount;
				String q1= "select * from items where itemcode ='"+rs.getString(2)+"'";
				PreparedStatement ps1 = (PreparedStatement) c.prepareStatement(q1);
				ResultSet rs1 = ps1.executeQuery();
				while(rs1.next()){
					int ca = rs1.getInt(9);
					if(ca==1){
						gcount=gcount+amount;
					}
					if(ca==2){
						wcount=wcount+amount;
					}
					if(ca==3){
						kcount=kcount+amount;
					}
					if(ca==4){
						ccount=ccount+amount;
					}
				}
			}}
			catch(Exception e){
				System.out.println(e);
			}
		System.out.println(qty);
		System.out.println(gcount);
		ObservableList<Data> List = FXCollections.observableArrayList(
    			new PieChart.Data("Gents",((float)(gcount/qty*100))),
    			new PieChart.Data("Ladies", ((float)(wcount/qty*100))),
    			new PieChart.Data("Kids",  ((float)(kcount/qty*100))),
    			new PieChart.Data("Cosmetics", ((float)(ccount/qty*100)))
    				    		);
    		Jgraph_cat.setData(List);
		
		
		
	}
	// Event Listener on JFXButton[#Jbtn_gen1].onAction
	@FXML
	public void genarete_piechart1(ActionEvent event) {
		// TODO Autogenerated
		ObservableList<Data> List = FXCollections.observableArrayList(
    			new PieChart.Data("Shirts", 10),
    			new PieChart.Data("Tshirts", 15),
    			new PieChart.Data("Denims", 10),
    			new PieChart.Data("Trousers", 20),
    			new PieChart.Data("Denims", 10),
    			new PieChart.Data("Denims", 10),
    			new PieChart.Data("Trousers", 15)
    			
    				    		);
    	Jgraph_scat.setData(List);
		
	}
	// Event Listener on JFXButton[#Jbtn_reports].onAction
	@FXML
	public void btn_reports(ActionEvent event) {
	
		
		try {
            new PrintReport().showReport();
	  	}
	  	catch(Exception e){
	  		System.out.println(e);
	  		
	  	}
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
		///Jcombo_cmonth.setItems(month);
		//Jcombo_scmonth.setItems(month);
		//addvaluetocatcombo();
		//Jcombo_cat.setItems(catlist);
		
	}
}
